# YAML configuration file for VEBuild

# # Identify directory names within VE_BUILD
#   - ve-lib
#   - ve-src
#   - ve-pkg-repo
#   - dependencies-repo
# # Identify repositories to clone / directories to visit to find VE to build
#   - List of directories (relative to VE_HOME)
#     - Will be searched recursively for DESCRIPTION files
#   - Don't mess with having VE clone those
# # Identify desired output:
#   - Local Installation
#   - Installer
# # Identify installer type to build if any (using "installer" target)
#   - Online Installer
#   - Online Installer plus VE Packages
#   - Offline Installer (VE Packages and Dependencies)

Output: Build                 # or Install; Build constructs ve-src, ve-lib and ve-pkg-repo
                              # Install also constructs dependencies-repo and ve.installers in the
                              # format called for by InstallerType
InstallerType: Online         # or VE-Offline or Offline (last implies dependencies are also offline)
                              # Online produces a VEBase bootstrap installer that installs
                              # everything from online locations.
                              # VE-Offline will install using built VE packages (either source or
                              # binary) for the current R version only.
                              # Offline will look for dependencies in the same place as the VE
                              # packages.
PackageType: Default          # or "Binary" or "Source" or "Both" - which repository branches to build
                              # for dependencies or VE Packages. "Binary" will be silently converted
                              # to "Source" for architectures like Unix which do not have binary R
                              # repository support
BuildTargets:                 # relative to Output - names of dependencies
  - ve.lib           : ve-lib
  - ve.src           : ve-src
  - ve.repository    : ve-pkg-repo
  - ve.dependencies  : dependencies-repo
  - ve.installers    : installers

PackageSources:               # absolute path or relative to VE_HOME
  - sources                   # name of sub-directory of VE_HOME
  - external                  # name of sub-directory of VE_HOME
  # - C:/Git-Repos/VE-Another-Source
